### ISSUE TITLE
Consolidate configuration [refactoring]

### ISSUE THREAD

**Issue by natolh** [DocTocToc/doctoctocbot#10]
• Currently some modules of the project contain hard coded constant variables that should be shared across the different modules and that are, for some, already present in the configuration file. For example the 'addtolist' module contain a hard coded 'bot_id' variable.
• Currently several modules implement their own way to load the configuration file, instead they should all use the 'getConfig' method of the 'cfg' module. For example in the 'addtolist' module on line 14 to 16.
• It seems there was a move to use json based configuration file, maybe that should be reconsidered (see footnotes 1 & 2) ?

1. https://softwareengineering.stackexchange.com/questions/351126/how-bad-of-an-idea-is-it-to-use-python-files-as-configuration-files
2. https://revelry.co/json-configuration-file-format

**Comment by jeromecc** [comment]
addtolist.py is not used anymore, docs.py (very bad name because now we have doctors and midwives among whitelisted users and pharmacists will probably follow soon) is adding users to the whitelist file.
I read critics about json as config file and i agree with most of them. Reason for switch was I couldn't easily loop through sublevels of ini files to build the "slugs" list: as more categories of users are added (eg: pharmacists soon) i wanted to just add a sublevel in json that the code would take up without further change and it was super easy to code for json (remember i was a Python beginner ;-).
If you can code something like this with cfg module and another format of config file I am ok. I lost a bit of time trying and it's not among my priorities but i will gladly accept a pull request.

**Comment by natolh** [comment]
So if 'addtolist' is not used anymore maybe the file could be deleted ? Is there any reason to keep it around ? If there is, maybe it can be kept in an 'archive' branch or maybe a big disclaimer comment should be added to the code ?

**Comment by jeromecc** [comment]
Codebase evolved to the point where there is no "standalone" bot script or module left, so I will go on removing all configuration stuff from the src/bot/conf folder to the main doctocnet/settings files. The Django bot app could still be used as a standalone app after a bit of tweaking though.
