### ISSUE TITLE
python3-psycopg2 dependency: pip or package?

### ISSUE THREAD

**Issue by jeromecc** [DocTocToc/doctoctocbot#12]
I run the bot on Debian Stretch. I got a warning following the introduction of the last pieces of code that depend on sqlalchemy:

/home/xxx/.local/lib/python3.5/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
""")

Question:

Should I use
 * Debian package python3-psycopg2
 * pip3 install psycopg2
 * pip3 install psycopg2-binary

I guess this psycopg2 dependency comes from the use of JSONB type in model/model.py:
    from sqlalchemy.dialects.postgresql import JSONB

Any idea @natolh?

**Comment by natolh** [comment]
I've no experience with that, when I was using PostgreSQL for my  projects it was running locally on macOS and deployed on Heroku. For macOS psycopg2 was installed using pip3 (maybe it was requiring a sudo, but it does not seem to be your problem there), as for Heroku no confie at all.
I'm a bit disturbed by the error message and what I read in the article you linked. It seems like you're installing psycopg2 for python 2... doctoctoc is written for python3 so you should run it on python3 and install dependencies using the python 3 pip tool (pip3)...?

A. HANNIET

Le 1 juin 2018 ? 07:45, jeromecc <notifications@github.com<mailto:notifications@github.com>> a ?crit :


I run the bot on Debian Stretch. I got a warning following the introduction of the last pieces of code that depend on sqlalchemy:

/home/xxx/.local/lib/python3.5/site-packages/psycopg2/init.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: http://initd.org/psycopg/docs/install.html#binary-install-from-pypi.
""")

Question:

Should I use

  *   Debian package python3-psycopg2
  *   pip3 install psycopg2
  *   pip3 install psycopg2-binary

I guess this psycopg2 dependency comes from the use of JSONB type in model/model.py:
from sqlalchemy.dialects.postgresql import JSONB

Any idea @natolh<https://github.com/natolh>?

-
